var integrants = [
    "エネルギー",
    "タンパク質",
    "脂質",
    "ナトリウム",
    "炭水化物",
    "ビタミンB",
    "ビタミンB2",
    "ビタミンB16",
    "ビタミンB12",
    "ビタミンC",
    "ナイアシン",
    "イノシトール",
    "カフェイン",
    "アルギニン",
    "パントテン酸",
    "バリン",
    "イソルイシン",
    "ルイシン",
    "リボース",
    "タウリン"
];

var drinks = [{
    name: "ライジン",
    image: "raizin.png",
    energy: 43.1,
    protein: 0,
    fat: 0,
    natrium: 21.1,
    carbohydrate: 10.6,
    vitamin_b: 0,
    vitamin_b2: 2,
    vitamin_b6: 2.2,
    vitamin_b12: 0,
    vitamin_c: 0,
    niacin: 11,
    inositol: 27,
    caffeine: 27,
    arginine: 0,
    pantothenic_acid: 0,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 0
}, {
    name: "レッドブル",
    image: "",
    energy: 46,
    protein: 0,
    fat: 0,
    natrium: 0,
    carbohydrate: 10.7,
    vitamin_b: 62,
    vitamin_b2: 0.09,
    vitamin_b6: 0,
    vitamin_b12: 2,
    vitamin_c: 0,
    niacin: 3,
    inositol: 0,
    caffeine: 80,
    arginine: 120,
    pantothenic_acid: 2,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 0
}, {
    name: "モンスターエナジー",
    image: "",
    energy: 0,
    protein: 0,
    fat: 0,
    natrium: 0,
    carbohydrate: 0,
    vitamin_b: 0,
    vitamin_b2: 0,
    vitamin_b6: 0,
    vitamin_b12: 0,
    vitamin_c: 0,
    niacin: 0,
    inositol: 0,
    caffeine: 0,
    arginine: 0,
    pantothenic_acid: 0,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 0
}, {
    name: "リポビタンD",
    image: "repo_d.png",
    energy: 0,
    protein: 0,
    fat: 0,
    natrium: 0,
    carbohydrate: 0,
    vitamin_b: 0,
    vitamin_b2: 5,
    vitamin_b6: 5,
    vitamin_b12: 0,
    vitamin_c: 0,
    niacin: 20,
    inositol: 50,
    caffeine: 50,
    arginine: 0,
    pantothenic_acid: 0,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 1000
}, {
    name: "アリナミンV",
    image: "",
    energy: 0,
    protein: 0,
    fat: 0,
    natrium: 0,
    carbohydrate: 0,
    vitamin_b: 0,
    vitamin_b2: 0,
    vitamin_b6: 0,
    vitamin_b12: 0,
    vitamin_c: 0,
    niacin: 0,
    inositol: 0,
    caffeine: 0,
    arginine: 0,
    pantothenic_acid: 0,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 0
}, {
    name: "チオビタドリンク",
    image: "",
    energy: 70,
    protein: 0,
    fat: 0,
    natrium: 0,
    carbohydrate: 0,
    vitamin_b: 0,
    vitamin_b2: 5,
    vitamin_b6: 5,
    vitamin_b12: 0,
    vitamin_c: 0,
    niacin: 0,
    inositol: 50,
    caffeine: 50,
    arginine: 0,
    pantothenic_acid: 0,
    valine: 0,
    isoleucine: 0,
    leucine: 0,
    d_ribose: 0,
    taurine: 1000
}];